### ISSUE TITLE
License for MikhailProg/elf?

### ISSUE THREAD

**Issue by pfalcon** [MikhailProg/json.awk#2]
Sorry for posting offtopic question, I initially posted as https://github.com/MikhailProg/elf/issues/1, but just noticed that that project has 0 watchers, i.e. not watched even by yourself, so you might not have had any notifications about the ticket. So, to catch attention, crossposting here. Thanks.

**Comment by MikhailProg** [comment]
Thanks that you've reached me here. I'll start watching my projects.
